### ISSUE TITLE
Upgrade to Vue 3

### ISSUE THREAD

**Issue by tobiasdiez** [JabRef/JabRefOnline#7]
Libraries compatible state:
- [x] fortawesome/vue-fontawesome: Has pre-release https://github.com/FortAwesome/vue-fontawesome/issues/230
- [x] nuxtjs/composition-api: no longer needed
- [x] vue/apollo-composable, vue/apollo-util, vue-apollo: v4 branch has support https://github.com/vuejs/vue-apollo/issues/1011, needs slightly different packages: https://v4.apollo.vuejs.org/guide-composable/setup.html#_1-install-vue-apollo-composable
- [ ] nuxt: Preview coming soon https://github.com/nuxt/nuxt.js/issues/5708 works in principle with vue 3, but there are a couple of issues:
   - [ ] https://github.com/nuxt/framework/discussions/560
   - [ ] no migration guide nuxt/bridge > nuxt3, https://v3.nuxtjs.org/docs/migration/overview
   - [ ] graphql: https://github.com/diizzayy/nuxt-graphql-client
- [x] pinia: compatible
- [x] portal-vue: probably replaced by teleport
- [x] vue-tailwind: work in progress https://github.com/alfonsobries/vue-tailwind/issues/127 and https://github.com/alfonsobries/vue-tailwind/issues/214 in the form of https://github.com/variantjs/vue
- [x] @he-tree/vue2: has vue 3 support
- [ ] https://github.com/nuxt-community/storybook/issues/330: missing nuxt 3 support
- [x] https://github.com/nuxt-community/tailwindcss-module/issues/386: missing nuxt 3 support
- [ ] https://github.com/tangbc/vue-virtual-scroll-list/issues/253 using https://github.com/supertiger1234/vue-3-virtual-scroll-list?

Maybe helpful:
- Reference implementation? https://github.com/lewebsimple/nuxt3-graphql

Issues depending on this:
- https://github.com/JabRef/JabRefOnline/pull/138
- https://github.com/JabRef/JabRefOnline/issues/139
- https://github.com/JabRef/JabRefOnline/pull/168: upgrade ts-loader to 9.x requires webpack 5
- Upgrade to yarn 3: https://dev.to/arcanis/yarn-3-0-performances-esbuild-better-patches-e07 https://yarnpkg.com/getting-started (there are currently problems with nuxt2 and yarn2) 
   - no install depends on https://github.com/nuxt/framework/issues/581 
- Use `script setup` syntax: https://v3.vuejs.org/api/sfc-script-setup.html#basic-syntax
- Use volar https://marketplace.visualstudio.com/items?itemName=johnsoncodehk.volar

**Comment by tobiasdiez** [comment]
There is nothing we can do at the moment, Nuxt 3 will probably still take a few months until public beta. See here: https://www.npmjs.com/package/nuxt3
