### ISSUE TITLE
Cleanup after nuxt-bridge update

### ISSUE THREAD

**Issue by tobiasdiez** [JabRef/JabRefOnline#770]
Tasks:
- [ ] Consider using auto-imports
- [ ] Add typescript check https://github.com/nuxt/framework/commit/d9c1aa6b02775e233111ed0341e7fd5d315f8847 https://github.com/JabRef/JabRefOnline/pull/637

Depending on other libs:
- [ ] Reenable tailconfig viewer. Blocked by https://github.com/nuxt-community/tailwindcss-module/issues/390
- [ ] Improve usage of tailwind, remove custom config once https://github.com/nuxt-community/tailwindcss-module/pull/399 is merged
- [ ] Remove patches to packages that are needed as workaround for https://github.com/apollographql/apollo-client/issues/9048
- [ ] Remove workaround/patch once https://github.com/nuxt/framework/issues/1967 is fixed
- [ ] Remove workaround/patch once https://github.com/nuxt-community/storybook/issues/343 is fixed
- [ ] Remove workaround/patch (from bridge) once https://github.com/nuxt-community/storybook/issues/342 is fixed
- [ ] Remove workaround/patch once https://github.com/nuxt-community/storybook/pull/344 is released
- [ ] Remove workaround/patch once https://github.com/nuxt-community/storybook/pull/345 is released
- [ ] Remove patch for typing info once https://github.com/nuxt/framework/pull/1996 https://github.com/nuxt/framework/pull/1995 is merged
- [ ] Remove patch for pinia once https://github.com/posva/pinia/pull/791 is merged
- [ ] Remove patch once https://github.com/nuxt/framework/issues/2000 is fixed
- [ ] Improve vue2 plugins https://github.com/nuxt/framework/issues/2037
